[WIP] Notification overhaul
AlexsLemonade/resources-portal pull request #346
Opened 2020-08-27 20:41 UTC by kurtwheeler

## Issue Number

#312 

## Purpose/Implementation Notes

Working on a lot things with this one. Will fill in more later, at the moment I just wanna be able to share easily.

## Types of changes

- New feature (non-breaking change which adds functionality)

## Functional tests

List out the functional tests you've completed to verify your changes work locally.

## Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots

Please attach any screenshots that illustrate these changes.

2020-09-01 21:36 UTC, kurtwheeler commented
@Philinphiladelphia I think this PR is finally ready for review!!!

@dvenprasad it might be good for you to look through the notifications_config.

I am really sorry about how huge this PR got, but it wasn't until just now that things stopped being broken.

I'm not sure that every notification that needs to be sent will be, but I'd rather address that in subsequent PRs. I'll look through tomorrow and see if I can spot any to make issues for.

2020-09-02 14:47 UTC, kurtwheeler commented
https://github.com/AlexsLemonade/resources-portal/issues/371 Has the notifications that I still need to generate and/or test for. I will do these in a subsequent PR once this is merged. (It shouldn't be too hard to knock all those out, the code to make a notification is pretty minimal at this point.)

2020-09-02 15:18 UTC, Philinphiladelphia commented on api/resources_portal/emailer.py
> +EMAIL_SOURCE_TEMPLATE = "Resources Portal Mail Robot <no-reply@{}>"
It might make sense to use this template in line 11 above, just so we have one unified source for the "Resources Portal Mail Robot" text.

2020-09-02 15:56 UTC, Philinphiladelphia commented on api/resources_portal/migrations/0026_auto_20200901_1642.py
> +# Generated by Django 2.2.13 on 2020-09-01 16:42
We're already up to 0026 on dev. This migration will need to be remade.

2020-09-02 16:19 UTC, Philinphiladelphia commented on api/resources_portal/test/models/test_notifications_config.py
> +            # We formtat the html different than the other fields.
```suggestion
            # We format the html different than the other fields.
```

2020-09-02 16:21 UTC, Philinphiladelphia commented on api/resources_portal/test/views/test_material_request_issue.py
> +        # Do we need an equivalent notification for this?
Probably not? It's a pretty minute action.

2020-09-02 18:41 UTC, dvenprasad requested changes
Most of it looks good. I've left some suggestions.

Also I noticed that these notifications were missing. 
- Sharer accepts a request and the request does not require any additional info from the requester 
- Escalating to Grants team

Is that being handled elsewhere?

2020-09-02 18:41 UTC, dvenprasad commented on api/resources_portal/models/notifications_config.py
> +        "body": "{requester_name} rejected a request for {material_category}, {material_name}.",
```suggestion
        "body": "{requester_name} cancelled a request for {material_category}, {material_name}.",
```

2020-09-02 18:41 UTC, dvenprasad commented on api/resources_portal/models/notifications_config.py
> +            " {material_category}, {material_name}:{provided_info_plain}\n\nReview items ({request_url})."
Can {provided_info_plain} be on a new line?

2020-09-02 18:41 UTC, dvenprasad commented on api/resources_portal/models/notifications_config.py
> +        "CTA": "View Request",
```suggestion
        "CTA": "View Fulfillment Notes",
```

2020-09-02 19:13 UTC, kurtwheeler commented
> Also I noticed that these notifications were missing. 
> - Sharer accepts a request and the request does not require any additional info from the requester 
> - Escalating to Grants team

> Is that being handled elsewhere?

Yes. The first should just be the IN_FULFILLMENT notification because if the request does not need any additional info from the requester it can skip the APPROVED status. The second has it's own PR/issue: https://github.com/AlexsLemonade/resources-portal/pull/373 and https://github.com/AlexsLemonade/resources-portal/issues/374

2020-09-02 20:34 UTC, dvenprasad commented
> The first should just be the IN_FULFILLMENT notification because if the request does not need any additional info from the requester

Yes, the emails to the requesters are good.
I think the sharer email for this scenario is not there, saying that the request was accepted.  i think it is this one:
```
Subject: Request for <resource type> accepted
Body: You/<Team Member> accepted a request for <resource type>, <resource name> from <Requester>.
CTA: View Request

Plain Text
<Full Name>,
You/<Team Member> accepted a request for <resource type>, <resource name> from <Requester>.

View request details.

The CCRR Team
-----
You are receiving this email because you subscribed to receive notifications from CCRR portal. Manage Notifications
Alex's Lemonade Stand Foundation
111 Presidential Blvd, Suite 203, Bala Cynwyd,  PA 19004
```

2020-09-04 19:38 UTC, kurtwheeler commented
Ah okay, I think I gotcha. Basically we need a notification to fire if it goes straight to IN_FULFILLMENT. The MATERIAL_REQUEST_SHARER_EXECUTED_MTA` notification says:`Please make arrangements to send the {material_category} to {requester_name}."` Should we include something like that in this one too?

2020-09-04 19:56 UTC, kurtwheeler commented
OK @Philinphiladelphia I think I addressed all your feedback (I've got https://github.com/AlexsLemonade/resources-portal/issues/372 to track the cron job.)

@dvenprasad I think I've now addressed your concerns as well, although I think maybe we should tweak the copy a tad for the notification I just added?

2020-09-08 15:32 UTC, dvenprasad commented
Okay, yeah let's add that sentence in. Good call 🚀

2020-09-08 15:32 UTC, dvenprasad approved these changes

2020-09-08 16:06 UTC, Philinphiladelphia reviewed
Looks like everything I mentioned got wrapped up. Merge when ready!

2020-09-08 17:37 UTC, merged